In [1]:
import pandas as pd

In [ ]:
# Multi Indexing
import pandas as pd
regions = ['North', 'North_east', 'South', 'South_east']
cities = ['Chicago', 'Detroit', 'Houston', 'Miami']
index=pd.MultiIndex.from_arrays([regions,cities],names=["regions","cities"])
data = {
    '2024_Sales': [150000, 95000, 120000, 185000],
    '2025_Sales': [165000, 98000, 130000, 190000]
}
sales_df=pd.DataFrame(data,index=index)
display(sales_df)
# here we are creating the multi indexing from the array
# which takes the atributes of arrays and the name of the column
#usually multi index is prefered when there is natural levels like region to city and so on

                    2024_Sales  2025_Sales
regions    cities
North      Chicago      150000      165000
North_east Detroit       95000       98000
South      Houston      120000      130000
South_east Miami        185000      190000

In [7]:
# navigating the north row
display(sales_df.loc["North"])

         2024_Sales  2025_Sales
cities
Chicago      150000      165000

In [9]:
sales_df.groupby(level="regions").sum()
sales_df.groupby(level="cities").sum()

         2024_Sales  2025_Sales
cities
Chicago      150000      165000
Detroit       95000       98000
Houston      120000      130000
Miami        185000      190000

In [ ]:
# Melting in Pandas
wide_df={
    "student_name":["Mani","gani","Devi","Narayana"],
    "math_scores":[40,50,60,70],
    "physics_score":[40,50,60,70],
    "chem_scores":[40,50,60,70]

}
df=pd.DataFrame(wide_df)
print(df)
# this is the wide form of the data
# we need to convret or melt this data using the statistical principle
# every column is variable and every row is the observation value
short_df=pd.melt(
    df,
    id_vars=["student_name"], 
    # the id_vars is used for the unchanged columns
    value_vars=["math_scores","physics_score","chem_scores"],
    # value_vars id used to define the values of the variables columns
    var_name="Subject",
    # var_name is used to define the name of the variable column
    value_name="Scores"

)
display(short_df)

  student_name  math_scores  physics_score  chem_scores
0         Mani           40             40           40
1         gani           50             50           50
2         Devi           60             60           60
3     Narayana           70             70           70

   student_name        Subject  Scores
0          Mani    math_scores      40
1          gani    math_scores      50
2          Devi    math_scores      60
3      Narayana    math_scores      70
4          Mani  physics_score      40
5          gani  physics_score      50
6          Devi  physics_score      60
7      Narayana  physics_score      70
8          Mani    chem_scores      40
9          gani    chem_scores      50
10         Devi    chem_scores      60
11     Narayana    chem_scores      70

In [11]:
# pd.pivot()
# this does the reverse of pd.melt() where it converts the long_df into wide_df
import pandas as pd

df_long_table = pd.DataFrame({
    'Student': ['Alice', 'Alice', 'Alice', 'Alice', 'Alice', 'Alice'],
    'Subject': ['Math', 'Math', 'Physics', 'Physics', 'Chemistry', 'Chemistry'],
    'Score': [95, 82, 89, 90, 92, 78]
})
df_long = pd.DataFrame({
    'Student': ['Alice', 'Bob', 'Alice', 'Bob', 'Alice', 'Bob'],
    'Subject': ['Math', 'Math', 'Physics', 'Physics', 'Chemistry', 'Chemistry'],
    'Score': [95, 82, 89, 90, 92, 78]
})

# print(df_long)
wide_df=df_long.pivot(index="Student",columns="Subject",values="Score")
display(wide_df)
# Difference between pivot and pivot table the pivot is only used for reshaping the data
# and doesnot handle duplicates and has aggregate functions
# where as on the other hand the pivot_table has aggregate functions and also handels duplicates
pivot_table_format=df_long_table.pivot_table(index="Student",columns="Subject",values="Score",aggfunc='mean')
display(pivot_table_format)
# Exercise
# convert the wide format into into longformat by pd.melt
wide_df_reset=wide_df.reset_index()
display(wide_df_reset.melt(id_vars="Student",value_vars=["Math", "Physics", "Chemistry"],var_name="Subject",value_name="Scores"))

Subject  Chemistry  Math  Physics
Student
Alice           92    95       89
Bob             78    82       90

Subject  Chemistry  Math  Physics
Student
Alice         85.0  88.5     89.5

  Student    Subject  Scores
0   Alice       Math      95
1     Bob       Math      82
2   Alice    Physics      89
3     Bob    Physics      90
4   Alice  Chemistry      92
5     Bob  Chemistry      78

In [15]:
credt_scores=[520,620,720,820]
bins=[500,600,700,800]
bin_labels=["low","medium","high"]
pd.cut(credt_scores,bins=bins,labels=bin_labels)

['low', 'medium', 'high', NaN]
Categories (3, str): ['low' < 'medium' < 'high']